In [28]:
import numpy as np

print(np.random.randn(3, 3))  # Normal distribution
print(np.random.rand(3, 3))  # Uniform distribution(0~1)

[[-0.4478258   0.66947051 -0.10066351]
 [ 0.01982533 -0.87893085 -1.16969525]
 [-1.13689468  0.25254107  0.19131336]]
[[0.8123572  0.3683304  0.67656779]
 [0.59864118 0.45852467 0.13203019]
 [0.22003724 0.75609348 0.13216752]]


In [ ]:
a = np.array([1, 2, 3, 4])  # list 가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype)  # data type
print(a.shape)
print(a[0])

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
1


In [ ]:
b = np.array([1.2, 3.1, 4])
print(b.dtype)  # 하나라도 실수면 자동으로 실수 타입
a = np.array(2**65 - 1)  # 자동으로 오버플로우 안 나게끔 함
print(a)
print(a.dtype)

float64
36893488147419103231
object


In [ ]:
A = np.array([[1, 2], [3, 4]])
# A = np.array([[1, 2], [3, 4, 5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim)  # 차원의 수
print(A.size)  # 전체 성분의 수

[[1 2]
 [3 4]]
(2, 2)
2
4


In [ ]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros((3, 3)))  # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
import torch

print(torch.zeros(3, 3))  # 근데 torch는 됨
print(np.arange(3, 10, 2))  # range랑 같은데 array로 만들어줌
print(np.arange(0, 1, 0.1))  # 소수점 가능
print(np.linspace(0, 1, 10))  # 0에서부터 1포함 10개로 리니어하게 쪼갬
print(np.linspace(0, 1, 10, endpoint=False))  # 0에서부터 1까지 (끝 포함 x) 10개로 쪼갬

[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = a + b
print(c)  # 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴

[5 7 9]


In [ ]:
A = np.array([[1, 2, 3], [1, 2, 3]])
B = np.array([[4, 5, 6], [1, 1, 1]])
C = A + B
D = A - B
print(C)
print(D)
print(A * B)  # 곱셈은? 성분끼리의 곱 (Hadamard product)
print(A / B)  # 나누기도 마찬가지
print(B**2)  # 제곱도 각 성분에 대해서 해준다

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[1, 2], [3, 4]])
print(A * B)
print(A @ B)  # 일반적인 행렬의 곱셈은 @

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [ ]:
# numpy의 인덱싱과 슬라이싱
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
# 행렬에 대한 인덱싱과 슬라이싱
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0, 2])
print(A[1, :])  # 1행, 전부 == A[1]
print(A[1, 0:3:2])
print(A[:, 2])  # 전부, 2열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[4 5 6]
[4 6]
[3 6 9]


In [ ]:
# boolean 인덱싱
a = [1, 2, 3, 4, 5, 3, 3]
print(a == 3)  # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같나? 다르다
A = np.array(
    [
        [
            1,
            2,
            3,
            4,
        ],
        [5, 3, 7, 3],
    ]
)
print(A == 3)  # 리스트와 달리 각 요소에 대해 비교해줌
print(A[A == 3])  # True, False가 달린 행렬로 인덱싱 가능
A[A == 3] = 100  # 그러면 이런 것도 가능하다 - 3과 같은 애를 100으로 바꿈
print(A)

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]


In [ ]:
A = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
B = np.array([True, False, False, True])  # 참고로 그냥 리스트여도 됨
print(A[B, :])  # 0행, 3행 슬라이싱

[[1 2]
 [7 8]]


In [ ]:
b = np.array([1, 2, 3, 4])
print(b)
print(b[[True, True, False, False]])
c = [1, 2, 3, 4]
# c[ [True, True, False, False] ] # error!

[1 2 3 4]
[1 2]


In [ ]:
# 3차원 행렬 인덱싱
A = np.array(
    [
        [[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]],
        [[12, 13, 14, 15], [16, 17, 18, 19], [20, 21, 22, 23]],
    ]
)
print(A)
print(A.shape)  # 대괄호가 하나 늘어나면 왼쪽 shape 값이 추가된다.
print(A[0, 1, 2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


In [ ]:
# numpy의 여러 함수들
A = np.random.randn(3, 3)  # 여긴 튜플로 안 줘도 됨
B = np.random.rand(3, 3)
print(A)
print(B)
print(A[A[:, 0] < 0, :])  # 0번째 열이 음수인 행들

[[ 0.31347643 -0.31670587  1.35786994]
 [ 1.22893293  2.10322639 -0.00396429]
 [-0.27361773  0.28901863 -0.72725245]]
[[0.85081124 0.78164211 0.70268538]
 [0.54164481 0.6611405  0.8181554 ]
 [0.36599202 0.72734406 0.84282962]]
[[-0.27361773  0.28901863 -0.72725245]]


In [43]:
A = np.random.randn(3, 3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1)))
print(np.log10(10))
print(np.log2(2))
print(np.round(A))  # 반올림
print(np.round(A, 2))  # 소수점 둘째 자리까지
print(np.floor(A))  # 내림
print(np.ceil(A))  # 올림
print(np.sin(np.pi / 6))
print(np.cos(np.pi / 3))
print(np.tan(np.pi / 4))
print(np.tanh(-10))

[[ 0.84514416 -0.57759971 -1.86787862]
 [ 0.42374962 -0.83394158 -0.2837345 ]
 [-0.20467451  1.62422742 -0.06352756]]
[[0.84514416 0.57759971 1.86787862]
 [0.42374962 0.83394158 0.2837345 ]
 [0.20467451 1.62422742 0.06352756]]
[[0.91931722 0.75999981 1.36670356]
 [0.65096054 0.91320402 0.53266734]
 [0.45240967 1.27445181 0.25204674]]
[[2.32831343 0.5612439  0.15445096]
 [1.52767904 0.43433395 0.75296653]
 [0.81491252 5.07449707 0.93844825]]
[[-0.16824807 -0.54887419  0.62480336]
 [-0.85861252 -0.18159193 -1.25971635]
 [-1.58633433  0.48503227 -2.75628143]]
1.0
1.0
1.0
[[ 1. -1. -2.]
 [ 0. -1. -0.]
 [-0.  2. -0.]]
[[ 0.85 -0.58 -1.87]
 [ 0.42 -0.83 -0.28]
 [-0.2   1.62 -0.06]]
[[ 0. -1. -2.]
 [ 0. -1. -1.]
 [-1.  1. -1.]]
[[ 1. -0. -1.]
 [ 1. -0. -0.]
 [-0.  2. -0.]]
0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [44]:
print(np.nan)  # not a number
# print(np.log(-1)) # error
print(np.isnan([1, 2, np.nan, 3, 4]))
print(np.isinf([1, 2, 3, 4, np.inf]))

nan
[False False  True False False]
[False False False False  True]


In [45]:
A = np.random.randn(3, 4)
print(A)
print(np.max(A))
print(np.max(A, axis=0))
print(np.max(A, axis=1))
print(np.max(A, axis=0, keepdims=True))
print(np.max(A, axis=1, keepdims=True))
print(np.min(A))
print(np.min(A, axis=0))
print(np.min(A, axis=1))
print(np.argmax(A))
print(np.argmax(A, axis=0))  # 각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A, axis=1))  # 각 행에서 가장 큰 애가 존재하는 인덱스

[[ 0.72645734  1.27790481  0.64010646 -0.02793626]
 [ 0.35766496 -0.16117452  0.86482776 -1.76189239]
 [-0.87946497 -1.29410932 -0.43280258 -0.5958925 ]]
1.2779048132018238
[ 0.72645734  1.27790481  0.86482776 -0.02793626]
[ 1.27790481  0.86482776 -0.43280258]
[[ 0.72645734  1.27790481  0.86482776 -0.02793626]]
[[ 1.27790481]
 [ 0.86482776]
 [-0.43280258]]
-1.7618923898381114
[-0.87946497 -1.29410932 -0.43280258 -1.76189239]
[-0.02793626 -1.76189239 -1.29410932]
1
[0 0 1 0]
[1 2 2]


In [46]:
a = np.random.randn(6, 1)
print(a)
a_sorted = np.sort(a, axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

[[ 0.16014469]
 [ 0.07665256]
 [ 0.68944191]
 [-0.53143957]
 [ 0.91285801]
 [-0.58918607]]
[[-0.58918607]
 [-0.53143957]
 [ 0.07665256]
 [ 0.16014469]
 [ 0.68944191]
 [ 0.91285801]]
[[ 0.91285801]
 [ 0.68944191]
 [ 0.16014469]
 [ 0.07665256]
 [-0.53143957]
 [-0.58918607]]


In [ ]:
a = np.random.randn(1, 6)
print(a)
a_sorted = np.sort(a, axis=1)
print(a_sorted)
print(np.fliplr(a_sorted))

[[-2.07153119  0.81047956 -1.48778379  1.25859794 -0.52965426 -0.82752423]]
[[-2.07153119 -1.48778379 -0.82752423 -0.52965426  0.81047956  1.25859794]]
[[ 1.25859794  0.81047956 -0.52965426 -0.82752423 -1.48778379 -2.07153119]]


In [49]:
A = np.random.randn(3, 4)
print(A)
print(np.sum(A))  # 합
print(np.sum(A, axis=1))
print(np.sum(A, axis=1, keepdims=True))
print(np.mean(A))  # 평균
print(np.mean(A, axis=1))
print(np.mean(A, axis=1, keepdims=True))  # 3행 1열짜리 2D array
print(np.std(A))  # standard deviation 표준 편차
print(np.std(A, axis=1))
print(np.std(A, axis=1, keepdims=True))

[[ 0.38795888 -1.78738618  1.85597478  0.26972888]
 [ 0.21940486 -1.21451568 -1.41015276  0.3408119 ]
 [ 1.70994154  0.69881099  0.88150747 -0.58079737]]
1.3712873159093117
[ 0.72627636 -2.06445168  2.70946264]
[[ 0.72627636]
 [-2.06445168]
 [ 2.70946264]]
0.11427394299244265
[ 0.18156909 -0.51611292  0.67736566]
[[ 0.18156909]
 [-0.51611292]
 [ 0.67736566]]
1.1128208667911954
[1.29718813 0.80037182 0.82026229]
[[1.29718813]
 [0.80037182]
 [0.82026229]]


In [50]:
A = np.random.randint(1, 5, size=(12,))
print(A)
print(A.shape)
B = A.reshape(2, 2, 3)
print(B)
print(B.ndim)  # 3차원 행렬이다

[4 2 2 3 1 3 1 4 1 3 2 1]
(12,)
[[[4 2 2]
  [3 1 3]]

 [[1 4 1]
  [3 2 1]]]
3


In [51]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 1])
print(a @ b.T)
print(np.sum(a * b))

9
9


In [52]:
a = a.reshape(3, 1)
b = b.reshape(3, 1)
print(a.transpose() @ b)
print(a.T @ b)
print(a @ b.T)

[[9]]
[[9]]
[[2 2 1]
 [4 4 2]
 [6 6 3]]


In [53]:
A = np.random.randn(4, 3, 2)
print(A.transpose(0, 2, 1).shape)

(4, 2, 3)


In [54]:
A = np.arange(20)
print(A)
print(A.reshape(4, 5))
print(A.reshape(4, -1).shape)  # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2, 5, -1).shape)
print(A.reshape(2, -1, 5).shape)
print(A.reshape(1, -1).shape)  # 2차원 행 벡터
print(A.reshape(-1, 1).shape)  # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [55]:
x = np.random.randn(2, 3, 4, 5, 6)
print(x[1, 2, :, :, :].shape)
print(x[1, 2, ...].shape)  # x[1,2,...] 는 x[1,2,:,:,:] 와 같습니다.
print(x[:, :, :, :, 3].shape)
print(x[..., 3].shape)
print(x[1, :, :, 3, :].shape)
print(x[1, ..., 3, :].shape)

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [56]:
A = np.ones((2, 2))
B = np.zeros((2, 2))
C = np.hstack([A, B])
D = np.vstack([A, B])
E = np.block([A, B])
F = np.block([[A], [B]])
G = np.block([[[A]], [[B]]])
print(A)
print(B)
print(C)
print(D)
print(E)
print(F)
print(G)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[0. 0.]
  [0. 0.]]]


In [ ]:
A = np.random.randn(1, 1, 1, 3, 1, 1, 4, 1)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0, 2, 4, 5)).shape)

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [59]:
A = np.random.randn(3, 4)
A1 = A[np.newaxis, ...]  # np.newaxis is None <- True
print(np.newaxis is None)
print(A1.shape)
A2 = A[..., np.newaxis]
print(A2.shape)
A3 = A[:, np.newaxis, :]
print(A3.shape)

True
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)


In [60]:
A1 = np.expand_dims(A, axis=(0))
print(A1.shape)
A2 = np.expand_dims(A, axis=(2))
print(A2.shape)
A3 = np.expand_dims(A, axis=(1))
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)


In [61]:
A1 = A.reshape(1, 3, 4)
print(A1.shape)
A2 = A.reshape(3, 4, 1)
print(A2.shape)
A3 = A.reshape(3, 1, 4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)


In [62]:
A = np.random.randn(3, 4)
B = np.random.randn(3, 4)
C = np.array([A, B])
print(A.shape)
print(B.shape)
print(C.shape)

(3, 4)
(3, 4)
(2, 3, 4)
